Twitter Demo Link Not Working
GorvGoyl/Clone-Wars pull request #214
Opened 2023-03-07 09:44 UTC by rajrr214

2023-04-10 09:38 UTC, iamrishupatel requested changes

2023-04-10 09:38 UTC, iamrishupatel commented on README.md
> +| Twitter                        | [twitter-geek.netlify.app](https://twitter-geek.netlify.app/#/) <br/> [github.com (screenshot)](https://github.com/RisingGeek/twitter-clone/blob/master/Live/feed.pn
Can you please remove this entry as well?

2023-04-10 09:39 UTC, iamrishupatel commented on README.md
> +| Twitter                        | [twitter-geek.netlify.app](https://twitter-geek.netlify.app/#/) <br/> [github.com (screenshot)](https://github.com/RisingGeek/twitter-clone/blob/master/Live/feed.pn
https://twitter-geek.netlify.app/#/
This link is not working as well.

2023-06-18 19:16 UTC, iamrishupatel commented
@fixelrr Could you make the required changes and resolve the merge conflict

2023-09-25 11:53 UTC, Pritamgit2002 commented
Provide demo link

2023-09-25 11:53 UTC, closed without merging