Added DisneyPlus Clone
GorvGoyl/Clone-Wars pull request #231
Opened 2023-07-05 05:51 UTC by Mannxxx

I've added disneyplus clone keeping in mind the alphabetical order. The link is working properly and the quality is also amazing. Worth adding to the list.

2023-07-05 07:13 UTC, crazy-man22 commented
> I've added disneyplus clone keeping in mind the alphabetical order. The link is working properly and the quality is also amazing. Worth adding to the list.

the live demo link is not working

2023-07-05 15:02 UTC, Mannxxx commented
@crazy-man22. The issue is from the db and hosting but it should work fine in your project

2023-07-05 16:46 UTC, crazy-man22 commented
> @crazy-man22. The issue is from the db and hosting but it should work fine in your project

if it's your project, you can deploy it on Vercel.
The README has to have a correct demo link so that vistors can try it online easily

2023-09-25 08:35 UTC, Pritamgit2002 requested changes

2023-09-25 08:35 UTC, Pritamgit2002 commented on README.md
> +| Disneyplus                        | [github.com (screenshot)](https://disney-clone-d1e27.web.app/)                                             | [GitHub](https://github.com/CleverProgrammers/cp-dis
Demo Link is not working !!!!

2023-09-25 11:52 UTC, Pritamgit2002 commented
provide demo link

2023-09-25 11:52 UTC, closed without merging